// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games(white_player_id)
    VALUES(
        $1
    )
    RETURNING game_id, white_player_id, black_player_id, status, turn, board_state, created_at
`

func (q *Queries) CreateGame(ctx context.Context, whitePlayerID uuid.NullUUID) (Game, error) {
	row := q.db.QueryRowContext(ctx, createGame, whitePlayerID)
	var i Game
	err := row.Scan(
		&i.GameID,
		&i.WhitePlayerID,
		&i.BlackPlayerID,
		&i.Status,
		&i.Turn,
		&i.BoardState,
		&i.CreatedAt,
	)
	return i, err
}

const getGame = `-- name: GetGame :one
SELECT game_id, white_player_id, black_player_id, status, turn, board_state, created_at FROM games WHERE game_id = $1
`

func (q *Queries) GetGame(ctx context.Context, gameID uuid.UUID) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGame, gameID)
	var i Game
	err := row.Scan(
		&i.GameID,
		&i.WhitePlayerID,
		&i.BlackPlayerID,
		&i.Status,
		&i.Turn,
		&i.BoardState,
		&i.CreatedAt,
	)
	return i, err
}

const joinGame = `-- name: JoinGame :one
UPDATE games 
SET black_player_id = $2, status = 'active' WHERE game_id = $1
RETURNING game_id, white_player_id, black_player_id, status, turn, board_state, created_at
`

type JoinGameParams struct {
	GameID        uuid.UUID
	BlackPlayerID uuid.NullUUID
}

func (q *Queries) JoinGame(ctx context.Context, arg JoinGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, joinGame, arg.GameID, arg.BlackPlayerID)
	var i Game
	err := row.Scan(
		&i.GameID,
		&i.WhitePlayerID,
		&i.BlackPlayerID,
		&i.Status,
		&i.Turn,
		&i.BoardState,
		&i.CreatedAt,
	)
	return i, err
}

const updateBoardState = `-- name: UpdateBoardState :one
UPDATE games
SET board_state = $2, turn = $3 WHERE game_id = $1
RETURNING game_id, white_player_id, black_player_id, status, turn, board_state, created_at
`

type UpdateBoardStateParams struct {
	GameID     uuid.UUID
	BoardState string
	Turn       PlayerColor
}

func (q *Queries) UpdateBoardState(ctx context.Context, arg UpdateBoardStateParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, updateBoardState, arg.GameID, arg.BoardState, arg.Turn)
	var i Game
	err := row.Scan(
		&i.GameID,
		&i.WhitePlayerID,
		&i.BlackPlayerID,
		&i.Status,
		&i.Turn,
		&i.BoardState,
		&i.CreatedAt,
	)
	return i, err
}

const updateGameStatus = `-- name: UpdateGameStatus :one
UPDATE games
set status = $2 WHERE game_id = $1
RETURNING game_id, white_player_id, black_player_id, status, turn, board_state, created_at
`

type UpdateGameStatusParams struct {
	GameID uuid.UUID
	Status GameStatus
}

func (q *Queries) UpdateGameStatus(ctx context.Context, arg UpdateGameStatusParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, updateGameStatus, arg.GameID, arg.Status)
	var i Game
	err := row.Scan(
		&i.GameID,
		&i.WhitePlayerID,
		&i.BlackPlayerID,
		&i.Status,
		&i.Turn,
		&i.BoardState,
		&i.CreatedAt,
	)
	return i, err
}
