// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type GameStatus string

const (
	GameStatusWaiting  GameStatus = "waiting"
	GameStatusActive   GameStatus = "active"
	GameStatusComplete GameStatus = "complete"
)

func (e *GameStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GameStatus(s)
	case string:
		*e = GameStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GameStatus: %T", src)
	}
	return nil
}

type NullGameStatus struct {
	GameStatus GameStatus
	Valid      bool // Valid is true if GameStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGameStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GameStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GameStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGameStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GameStatus), nil
}

type PlayerColor string

const (
	PlayerColorWhite PlayerColor = "white"
	PlayerColorBlack PlayerColor = "black"
)

func (e *PlayerColor) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlayerColor(s)
	case string:
		*e = PlayerColor(s)
	default:
		return fmt.Errorf("unsupported scan type for PlayerColor: %T", src)
	}
	return nil
}

type NullPlayerColor struct {
	PlayerColor PlayerColor
	Valid       bool // Valid is true if PlayerColor is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlayerColor) Scan(value interface{}) error {
	if value == nil {
		ns.PlayerColor, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlayerColor.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlayerColor) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlayerColor), nil
}

type Game struct {
	GameID        uuid.UUID
	WhitePlayerID uuid.NullUUID
	BlackPlayerID uuid.NullUUID
	Status        GameStatus
	Turn          PlayerColor
	BoardState    string
	CreatedAt     time.Time
}

type Move struct {
	MoveID int32
	GameID uuid.UUID
	Move   string
	Color  PlayerColor
}

type Player struct {
	ID             uuid.UUID
	Username       string
	HashedPassword string
}
