// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moves.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createMove = `-- name: CreateMove :one
INSERT INTO moves(game_id, move, color)
    VALUES(
        $1,
        $2,
        $3
    )
    RETURNING move_id, game_id, move, color
`

type CreateMoveParams struct {
	GameID uuid.UUID
	Move   string
	Color  PlayerColor
}

func (q *Queries) CreateMove(ctx context.Context, arg CreateMoveParams) (Move, error) {
	row := q.db.QueryRowContext(ctx, createMove, arg.GameID, arg.Move, arg.Color)
	var i Move
	err := row.Scan(
		&i.MoveID,
		&i.GameID,
		&i.Move,
		&i.Color,
	)
	return i, err
}

const getMoves = `-- name: GetMoves :many
SELECT move_id, game_id, move, color FROM moves WHERE game_id = $1
ORDER BY move_id
`

func (q *Queries) GetMoves(ctx context.Context, gameID uuid.UUID) ([]Move, error) {
	rows, err := q.db.QueryContext(ctx, getMoves, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Move
	for rows.Next() {
		var i Move
		if err := rows.Scan(
			&i.MoveID,
			&i.GameID,
			&i.Move,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
