// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: players.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players(id, username, hashed_password)
    VALUES(
        gen_random_uuid(),
        $1,
        $2
    )
    RETURNING id, username
`

type CreatePlayerParams struct {
	Username       string
	HashedPassword string
}

type CreatePlayerRow struct {
	ID       uuid.UUID
	Username string
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (CreatePlayerRow, error) {
	row := q.db.QueryRow(ctx, createPlayer, arg.Username, arg.HashedPassword)
	var i CreatePlayerRow
	err := row.Scan(&i.ID, &i.Username)
	return i, err
}

const getUserInfo = `-- name: GetUserInfo :one
SELECT id, hashed_password FROM players WHERE username = $1
`

type GetUserInfoRow struct {
	ID             uuid.UUID
	HashedPassword string
}

func (q *Queries) GetUserInfo(ctx context.Context, username string) (GetUserInfoRow, error) {
	row := q.db.QueryRow(ctx, getUserInfo, username)
	var i GetUserInfoRow
	err := row.Scan(&i.ID, &i.HashedPassword)
	return i, err
}
